FROM ubuntu:noble
RUN apt-get update && apt-get install -y locales software-properties-common && rm -rf /var/lib/apt/lists/* \
	&& localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8
RUN apt-get update -y && apt-get install -y git curl unzip build-essential xvfb
RUN 