services:
  retroarch:
    build: ./retroarch
    privileged: true
    # network_mode: host
    container_name: retroarch
    volumes:
      - ./roms:/app/roms
      # - /run/user/1000/pipewire-0:/tmp/pipewire-0
      - /run/udev:/run/udev
      # - /dev/:/dev/
    environment:
      - DISPLAY=:99
      - XDG_RUNTIME_DIR=/tmp/runtime
      # - PIPEWIRE_RUNTIME_DIR=/tmp
    networks:
      - retroarch_network
    devices:
      - /dev/video1 
      - /dev/input/event25
      - /dev/input/js0
      - /dev/uinput
    depends_on:
      - events-server

  events-server:
    container_name: virtual-gamepad
    privileged: true
    build: ./events-server
    ports:
      - "8090:8090"
    devices:
      - /dev/uinput
    networks:
      - retroarch_network
    
  webrtc:
    container_name:  webrtc
    image: mpromonet/webrtc-streamer:latest
    ports:
      - "8000:8000"
    networks:
      - retroarch_network
    devices:
      - /dev/video1 
    depends_on:
      - retroarch

  web-app:
    container_name: gui-app
    build: ./web-app
    ports:
      - "8001:80"
    networks:
      - retroarch_network
    devices:
      - /dev/video1 
    depends_on:
      - webrtc

networks:
  retroarch_network:
    driver: bridge
